apiVersion: apps/v1
kind: Deployment
metadata:
  name: line-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: line-app
  template:
    metadata:
      labels:
        app: line-app
    spec:
      containers:
      - name: line-app
        image: ${DOCKER_IMAGE}:${DOCKER_TAG}
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
